### ISSUE TITLE
Tags missing

### ISSUE THREAD

**Issue by dotlambda** [ua-parser/uap-rust#19]
ua-parser-rs has two versions on https://pypi.org/project/ua-parser-rs/#history but the corresponding tags are missing from https://github.com/ua-parser/uap-rust/tags.

**Comment by masklinn** [comment]
Why would it have tags?

**Comment by dotlambda** [comment]
I'm trying to package ua-parser-rs for Nixpkgs in https://github.com/NixOS/nixpkgs/pull/360066.
But I'd prefer to fetch the source code from GitHub rather than an sdist from PyPI. That's why tags corresponding to the versions published on PyPI would be useful.

**Comment by masklinn** [comment]
Sounds fair.

However the repository has 3 different things which might need to be packaged separately (two Rust crates and a Python package, I have no idea how nix handles either). How should that be handled, with tag prefixes to differentiate them?

**Comment by dotlambda** [comment]
> with tag prefixes to differentiate them?

That sounds like a good idea.

**Comment by masklinn** [comment]
There you go, I got the ua-parser-rs commits from the workflow runs which uploaded the wheels so they *should* be right. They're prefixed by `ua-parser-rs-` followed by the version number.

I also noted down that I should formalise this before the next release, so the next one should hopefully be properly tagged.

**Comment by dotlambda** [comment]
Thanks a lot!

**Comment by dotlambda** [comment]
Just one more thing: Would you consider committing a `Cargo.lock`?

**Comment by masklinn** [comment]
Do you mean committing it to the repo? I don’t really mind in principle. I think I’d need to update the test workflow to test with all relevant versions of the dependencies though.

**Comment by dotlambda** [comment]
> Do you mean committing it to the repo?

Yes.



> I think I’d need to update the test workflow to test with all relevant versions of the dependencies though.

I assume that currently the latest version of each dependency is tested? The same could be achieved by e.g. dependabot automatically updating all dependencies.

**Comment by masklinn** [comment]
> I assume that currently the latest version of each dependency is tested?

Currently it would use the latest version of each dependency within the dependency bounds of cargo.toml, which defaults to semver compatibility (somewhat extended).

With a cargo.lock this forward compatibility check would not happen anymore, the tests would run against whatever was pinned. Which would be a problem, because as far as I know the lock file is not considered when using a library.

> The same could be achieved by e.g. dependabot automatically updating all dependencies.

No, that does dependency chasing, which goes a lot further and may be plain undesirable.

**Comment by dotlambda** [comment]
> No, that does dependency chasing, which goes a lot further and may be plain undesirable.

I would hope there's a way to configure it to only update crates to versions within the bounds specified in `Cargo.toml`. Though I'm honestly not very familiar with it.

**Comment by masklinn** [comment]
Added Cargo.lock to the repo in #21
